### ISSUE TITLE
Snap support for windows 11

### ISSUE THREAD

**Issue by MichelMichels** [sygmond/WindowChromeMultiscreen#5]
Snap layout integration would be nice. 

![image](https://github.com/sygmond/WindowChromeMultiscreen/assets/6505319/57ad86ce-0fa7-4dcc-b831-c68f469d4c64)

I'll look into it

**Comment by sygmond** [comment]
@MichelMichels I'm still fan of Windows 10, using 11 only for work, but didn't run yet the app on 11. Isn't Windows 11 do that by default? Would be a nice integration indeed.
